# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[\u256d\u2500](purple)\
$time\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$nodejs\
$python\
$dotnet\
$fill\
$line_break\
[\u2570\u2500](purple)\
$character"""

[nodejs]
format = "[| $symbol($version )]($style)"

[python]
symbol = " "
format = '[| $symbol($version)]($style)[( \($virtualenv\)) ](fg:green)'

[dotnet]
format = "[| $symbol($version )]($style)"
detect_extensions =	['sln', 'csproj', 'fsproj', 'xproj']

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " "
truncation_symbol = '…/'
truncation_length = 1
truncate_to_repo = false
format = '[ |  $path]($style)[$read_only]($read_only_style) '

[character]
success_symbol = "[ ❯](purple)"
error_symbol = "[ ❯](red)"
vicmd_symbol = "[ ❮](green)"

[git_branch]
symbol = " "
format = "[| $symbol$branch]($style) "
style = "fg:purple"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[memory_usage]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
time_format = "%R"
style = "fg:bold purple"
format = "[ $time]($style)"
